<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1039.0" />
    <PackageReference Include="VirtoCommerce.ReturnModule.Data" Version="3.1001.0" />
    <PackageReference Include="VirtoCommerce.MarketplaceVendorModule.Data" Version="3.1001.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Virtocommerce.MarketplaceReturn.Core\Virtocommerce.MarketplaceReturn.Core.csproj" />
  </ItemGroup>
</Project>
